### PR TITLE
Optimisations

### PR DESCRIPTION
**Pull request by schriftgestalt**

### CODE REVIEW

**Comment by simoncozens** [comment]
Too much magic?

screen shot 2016-07-17 at 20 47 48
screen shot 2016-07-17 at 20 49 39

**Comment by simoncozens** [comment]
Looks like the bug was introduced in a0a81f3.

**Comment by schriftgestalt** [comment]
I'll have a look.

**Comment by schriftgestalt** [comment]
fixed it in 3c61b1e573f433f7723

**Comment by simoncozens** [comment]
Better, but still a bit of strangeness:

screen shot 2016-07-18 at 06 22 34

**Comment by simoncozens** [comment]
The bug is somewhere in line 62.

**Comment by simoncozens** [comment]
Got it! P0 was being used uninitialized.

**Pull request merged**
